name: CI

on: [push, pull_request]

jobs:

  build-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04, ubuntu-18.04]
    steps:
      - uses: actions/checkout@v3
      - name: build
        run: uname -a
